---
- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution_file_variety | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - promtail_install
    - promtail_configure
    - promtail_run

- import_tasks: preflight.yml
  tags:
    - promtail_install
    - promtail_configure
    - promtail_run

- import_tasks: install.yml
  become: true
  tags:
    - promtail_install

- import_tasks: configure.yml
  become: true
  tags:
    - promtail_configure

- name: Ensure promtail is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: promtail
    enabled: true
  tags:
    - promtail_run
